// app/proyek/laporan/helpers/report-styles.ts

import React from 'react';

export const reportStyles: Record<string, React.CSSProperties> = {
  page: { background: '#f5f7fb', minHeight: '100vh', padding: '24px' },
  container: { maxWidth: 1240, margin: '0 auto', display: 'grid', gap: 20 },
  card: {
    background: '#fff',
    borderRadius: 16,
    padding: 20,
    boxShadow: '0 6px 24px rgba(15,23,42,0.06)',
  },
  subCard: {
    background: '#f8fafc',
    borderRadius: 14,
    padding: 16,
    border: '1px solid #e2e8f0',
  },
  tableCard: {
    background: '#f8fafc',
    borderRadius: 14,
    padding: 16,
    border: '1px solid #e2e8f0',
  },
  headerRow: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: 16,
    alignItems: 'flex-start',
  },
  headerActions: { display: 'flex', gap: 12, flexWrap: 'wrap' },
  pageTitle: { margin: 0, fontSize: 32, fontWeight: 800, color: '#0f172a' },
  pageDesc: { margin: '8px 0 0', color: '#475569', maxWidth: 720 },
  sectionTitle: { margin: 0, fontSize: 22, fontWeight: 700, color: '#0f172a' },
  subTitle: { margin: 0, fontSize: 18, fontWeight: 700, color: '#0f172a' },
  summaryTitle: { margin: 0, fontSize: 18, fontWeight: 700, color: '#0f172a' },
  tableTitle: {
    margin: '0 0 12px',
    fontSize: 16,
    fontWeight: 700,
    color: '#0f172a',
  },
  metaText: { color: '#475569', margin: '8px 0 0' },
  metaGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
    gap: 12,
    marginTop: 16,
  },
  metaItem: {
    background: '#f8fafc',
    borderRadius: 12,
    padding: 14,
    display: 'grid',
    gap: 6,
    border: '1px solid #e2e8f0',
  },
  summaryBox: {
    background: '#eef6ff',
    border: '1px solid #bfdbfe',
    borderRadius: 14,
    padding: 16,
    marginTop: 16,
  },
  gridTwo: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
    gap: 16,
    marginTop: 16,
  },
  expertBlock: {
    marginTop: 18,
    paddingTop: 18,
    borderTop: '1px solid #e2e8f0',
    display: 'grid',
    gap: 16,
  },
  expertHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: 16,
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  crPill: {
    background: '#f8fafc',
    border: '1px solid #cbd5e1',
    color: '#0f172a',
    padding: '8px 12px',
    borderRadius: 999,
  },
  tableWrap: { overflowX: 'auto', marginTop: 16 },
  table: { width: '100%', borderCollapse: 'collapse', minWidth: 560 },
  th: {
    textAlign: 'left',
    padding: 12,
    background: '#e2e8f0',
    color: '#0f172a',
    fontSize: 14,
    fontWeight: 700,
  },
  td: {
    padding: 12,
    borderBottom: '1px solid #e2e8f0',
    color: '#334155',
    fontSize: 14,
  },
  tdHead: {
    padding: 12,
    borderBottom: '1px solid #e2e8f0',
    color: '#0f172a',
    fontWeight: 700,
    fontSize: 14,
  },
  btnPrimary: {
    background: '#0f766e',
    color: '#fff',
    border: 'none',
    borderRadius: 12,
    padding: '12px 16px',
    cursor: 'pointer',
    fontWeight: 700,
  },
  btnSecondary: {
    background: '#fff',
    color: '#0f172a',
    border: '1px solid #cbd5e1',
    borderRadius: 12,
    padding: '12px 16px',
    cursor: 'pointer',
    fontWeight: 700,
  },
  errorBox: {
    background: '#fef2f2',
    color: '#991b1b',
    border: '1px solid #fecaca',
    padding: 14,
    borderRadius: 12,
  },
  listItem: {
    padding: '10px 0',
    borderBottom: '1px solid #e2e8f0',
  },
  ul: {
    margin: '12px 0 0',
    paddingLeft: 20,
    color: '#334155',
  },
};